# Archivo de configuración
pantalla:
    ancho: 800 #pixels
    alto: 600 #pixels
configuracion:
    vel_personaje : 200
    margen_scroll : 50
entidades:
    - nombre: tierra
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 0 #pixels
      ancho_base: 1 #tiles
      alto_base: 1 #tiles
      imagen:
        - [tierra.png]
    - nombre: hielo
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 0 #pixels
      ancho_base: 1 #tiles
      alto_base: 1 #tiles
      imagen:
        - [hielo.png]
    - nombre: pasto
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 0 #pixels
      ancho_base: 1 #tiles
      alto_base: 1 #tiles
      imagen:
        - [pasto.png]
    - nombre: agua
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 0 #pixels
      ancho_base: 1 #tiles
      alto_base: 1 #tiles
      imagen:
        - [agua.png]
    - nombre: cemento
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 0 #pixels
      ancho_base: 1 #tiles
      alto_base: 1 #tiles
      imagen:
        - [cemento.png]
    - nombre: arena
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 0 #pixels
      ancho_base: 1 #tiles
      alto_base: 1 #tiles
      imagen:
        - [arena.png]
    - nombre: granja_llamas
      imagen:
        - [FireFarm01.png,FireFarm02.png,FireFarm03.png,FireFarm04.png,FireFarm05.png,FireFarm06.png,FireFarm07.png,FireFarm08.png,FireFarm09.png,FireFarm10.png,FireFarm11.png,FireFarm12.png,FireFarm13.png,FireFarm14.png,FireFarm15.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 110 #pixels
      pixel_ref_y: 20 #pixels
      delay: 5
    - nombre: casa_molino
      imagen:
        - [CasaB01.png,CasaB02.png,CasaB03.png,CasaB04.png,CasaB05.png,CasaB06.png,CasaB07.png,CasaB08.png,CasaB09.png,CasaB10.png]
      ancho_base: 3 #tiles
      alto_base: 3 #tiles
      pixel_ref_x: 150 #pixels
      pixel_ref_y: 20 #pixels
      delay: 0
    - nombre: castillo
      imagen:
        - [castillo01.png,castillo02.png,castillo03.png,castillo04.png,castillo05.png]
      ancho_base: 4 #tiles
      alto_base: 4 #tiles
      pixel_ref_x: 210 #pixels
      pixel_ref_y: 55 #pixels
      delay: 5
    - nombre: casa_selva
      imagen:
        - [CasaC01.png,CasaC02.png,CasaC03.png,CasaC04.png,CasaC04.png,CasaC06.png]
      ancho_base: 3 #tiles
      alto_base: 3 #tiles
      pixel_ref_x: 150 #pixels
      pixel_ref_y: 20 #pixels
      delay: 5
    - nombre: rancho
      imagen:
        - [CasaA01.png,CasaA02.png,CasaA03.png,CasaA04.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 100 #pixels
      pixel_ref_y: 10 #pixels
      delay: 1
    - nombre: molino
      imagen:
        - [molino01.png,molino02.png,molino03.png,molino04.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 100 #pixels
      pixel_ref_y: 20 #pixels
      delay: 0
    - nombre: mini_mapa
      imagen:
        - [MiniMapa01.png,MiniMapa02.png,MiniMapa03.png,MiniMapa04.png,MiniMapa05.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 100 #pixels
      pixel_ref_y: 10 #pixels
      fps: 10
      delay: 3
    - nombre: violeta
      imagen:
        - [6Actor_N1.png,6Actor_N2.png,6Actor_N3.png,6Actor_N4.png,6Actor_N5.png,6Actor_N6.png]
        - [6Actor_NE1.png,6Actor_NE2.png,6Actor_NE3.png,6Actor_NE4.png,6Actor_NE5.png,6Actor_NE6.png]
        - [6Actor_E1.png,6Actor_E2.png,6Actor_E3.png,6Actor_E4.png,6Actor_E5.png,6Actor_E6.png]
        - [6Actor_SE1.png,6Actor_SE2.png,6Actor_SE3.png,6Actor_SE4.png,6Actor_SE5.png,6Actor_SE6.png]
        - [6Actor_S1.png,6Actor_S2.png,6Actor_S3.png,6Actor_S4.png,6Actor_S5.png,6Actor_S6.png]
        - [6Actor_SO1.png,6Actor_SO2.png,6Actor_SO3.png,6Actor_SO4.png,6Actor_SO5.png,6Actor_SO6.png]
        - [6Actor_O1.png,6Actor_O2.png,6Actor_O3.png,6Actor_O4.png,6Actor_O5.png,6Actor_O6.png]
        - [6Actor_NO1.png,6Actor_NO2.png,6Actor_NO3.png,6Actor_NO4.png,6Actor_NO5.png,6Actor_NO6.png]
      fps: 15
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 15 #pixels
    - nombre: guerrero
      imagen:
        - [actor1N1.png,actor1N2.png,actor1N3.png,actor1N4.png]
        - [actor1NE1.png,actor1NE2.png,actor1NE3.png,actor1NE4.png]
        - [actor1E1.png,actor1E2.png,actor1E3.png,actor1E4.png]
        - [actor1SE1.png,actor1SE2.png,actor1SE3.png,actor1SE4.png]
        - [actor1S1.png,actor1S2.png,actor1S3.png,actor1S4.png]
        - [actor1SO1.png,actor1SO2.png,actor1SO3.png,actor1SO4.png]
        - [actor1O1.png,actor1O2.png,actor1O3.png,actor1O4.png]
        - [actor1NO1.png,actor1NO2.png,actor1NO3.png,actor1NO4.png]
      ancho_base: 1 #tiles
      alto_base: 1 #tiles
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 10 #pixels
      fps: 10
    - nombre: vlad
      imagen:
        - [Vlad_N01.png,Vlad_N02.png,Vlad_N03.png,Vlad_N04.png,Vlad_N05.png,Vlad_N06.png,Vlad_N07.png,Vlad_N08.png,Vlad_N09.png]
        - [Vlad_NE01.png,Vlad_NE02.png,Vlad_NE03.png,Vlad_NE04.png,Vlad_NE05.png,Vlad_NE06.png,Vlad_NE07.png,Vlad_NE08.png,Vlad_NE09.png]
        - [Vlad_E01.png,Vlad_E02.png,Vlad_E03.png,Vlad_E04.png,Vlad_E05.png,Vlad_E06.png,Vlad_E07.png,Vlad_E08.png,Vlad_E09.png]
        - [Vlad_SE01.png,Vlad_SE02.png,Vlad_SE03.png,Vlad_SE04.png,Vlad_SE05.png,Vlad_SE06.png,Vlad_SE07.png,Vlad_SE08.png,Vlad_SE09.png]
        - [Vlad_S01.png,Vlad_S02.png,Vlad_S03.png,Vlad_S04.png,Vlad_S05.png,Vlad_S06.png,Vlad_S07.png,Vlad_S08.png,Vlad_S09.png]
        - [Vlad_SO01.png,Vlad_SO02.png,Vlad_SO03.png,Vlad_SO04.png,Vlad_SO05.png,Vlad_SO06.png,Vlad_SO07.png,Vlad_SO08.png,Vlad_SO09.png]
        - [Vlad_O01.png,Vlad_O02.png,Vlad_O03.png,Vlad_O04.png,Vlad_O05.png,Vlad_O06.png,Vlad_O07.png,Vlad_O08.png,Vlad_O09.png]
        - [Vlad_NO01.png,Vlad_NO02.png,Vlad_NO03.png,Vlad_NO04.png,Vlad_NO05.png,Vlad_NO06.png,Vlad_NO07.png,Vlad_NO08.png,Vlad_NO09.png]
        - [Vlad_Attack1_N01.png,Vlad_Attack1_N02.png,Vlad_Attack1_N03.png,Vlad_Attack1_N04.png,Vlad_Attack1_N05.png,Vlad_Attack1_N06.png,Vlad_Attack1_N07.png,Vlad_Attack1_N08.png,Vlad_Attack1_N09.png,Vlad_Attack1_N10.png,Vlad_Attack1_N11.png,Vlad_Attack1_N12.png]
        - [Vlad_Attack1_NE01.png,Vlad_Attack1_NE02.png,Vlad_Attack1_NE03.png,Vlad_Attack1_NE04.png,Vlad_Attack1_NE05.png,Vlad_Attack1_NE06.png,Vlad_Attack1_NE07.png,Vlad_Attack1_NE08.png,Vlad_Attack1_NE09.png,Vlad_Attack1_NE10.png,Vlad_Attack1_NE11.png,Vlad_Attack1_NE12.png]
        - [Vlad_Attack1_E01.png,Vlad_Attack1_E02.png,Vlad_Attack1_E03.png,Vlad_Attack1_E04.png,Vlad_Attack1_E05.png,Vlad_Attack1_E06.png,Vlad_Attack1_E07.png,Vlad_Attack1_E08.png,Vlad_Attack1_E09.png,Vlad_Attack1_E10.png,Vlad_Attack1_E11.png,Vlad_Attack1_E12.png]
        - [Vlad_Attack1_SE01.png,Vlad_Attack1_SE02.png,Vlad_Attack1_SE03.png,Vlad_Attack1_SE04.png,Vlad_Attack1_SE05.png,Vlad_Attack1_SE06.png,Vlad_Attack1_SE07.png,Vlad_Attack1_SE08.png,Vlad_Attack1_SE09.png,Vlad_Attack1_SE10.png,Vlad_Attack1_SE11.png,Vlad_Attack1_SE12.png]
        - [Vlad_Attack1_S01.png,Vlad_Attack1_S02.png,Vlad_Attack1_S03.png,Vlad_Attack1_S04.png,Vlad_Attack1_S05.png,Vlad_Attack1_S06.png,Vlad_Attack1_S07.png,Vlad_Attack1_S08.png,Vlad_Attack1_S09.png,Vlad_Attack1_S10.png,Vlad_Attack1_S11.png,Vlad_Attack1_S12.png]
        - [Vlad_Attack1_SO01.png,Vlad_Attack1_SO02.png,Vlad_Attack1_SO03.png,Vlad_Attack1_SO04.png,Vlad_Attack1_SO05.png,Vlad_Attack1_SO06.png,Vlad_Attack1_SO07.png,Vlad_Attack1_SO08.png,Vlad_Attack1_SO09.png,Vlad_Attack1_SO10.png,Vlad_Attack1_SO11.png,Vlad_Attack1_SO12.png]
        - [Vlad_Attack1_O01.png,Vlad_Attack1_O02.png,Vlad_Attack1_O03.png,Vlad_Attack1_O04.png,Vlad_Attack1_O05.png,Vlad_Attack1_O06.png,Vlad_Attack1_O07.png,Vlad_Attack1_O08.png,Vlad_Attack1_O09.png,Vlad_Attack1_O10.png,Vlad_Attack1_O11.png,Vlad_Attack1_O12.png]
        - [Vlad_Attack1_NO01.png,Vlad_Attack1_NO02.png,Vlad_Attack1_NO03.png,Vlad_Attack1_NO04.png,Vlad_Attack1_NO05.png,Vlad_Attack1_NO06.png,Vlad_Attack1_NO07.png,Vlad_Attack1_NO08.png,Vlad_Attack1_NO09.png,Vlad_Attack1_NO10.png,Vlad_Attack1_NO11.png,Vlad_Attack1_NO12.png]		
        - [Vlad_Bitting1_N01.png,Vlad_Bitting1_N02.png,Vlad_Bitting1_N03.png,Vlad_Bitting1_N04.png,Vlad_Bitting1_N05.png,Vlad_Bitting1_N06.png,Vlad_Bitting1_N07.png,Vlad_Bitting1_N08.png]
        - [Vlad_Bitting1_NE01.png,Vlad_Bitting1_NE02.png,Vlad_Bitting1_NE03.png,Vlad_Bitting1_NE04.png,Vlad_Bitting1_NE05.png,Vlad_Bitting1_NE06.png,Vlad_Bitting1_NE07.png,Vlad_Bitting1_NE08.png]
        - [Vlad_Bitting1_E01.png,Vlad_Bitting1_E02.png,Vlad_Bitting1_E03.png,Vlad_Bitting1_E04.png,Vlad_Bitting1_E05.png,Vlad_Bitting1_E06.png,Vlad_Bitting1_E07.png,Vlad_Bitting1_E08.png]
        - [Vlad_Bitting1_SE01.png,Vlad_Bitting1_SE02.png,Vlad_Bitting1_SE03.png,Vlad_Bitting1_SE04.png,Vlad_Bitting1_SE05.png,Vlad_Bitting1_SE06.png,Vlad_Bitting1_SE07.png,Vlad_Bitting1_SE08.png]
        - [Vlad_Bitting1_S01.png,Vlad_Bitting1_S02.png,Vlad_Bitting1_S03.png,Vlad_Bitting1_S04.png,Vlad_Bitting1_S05.png,Vlad_Bitting1_S06.png,Vlad_Bitting1_S07.png,Vlad_Bitting1_S08.png]
        - [Vlad_Bitting1_SO01.png,Vlad_Bitting1_SO02.png,Vlad_Bitting1_SO03.png,Vlad_Bitting1_SO04.png,Vlad_Bitting1_SO05.png,Vlad_Bitting1_SO06.png,Vlad_Bitting1_SO07.png,Vlad_Bitting1_SO08.png]
        - [Vlad_Bitting1_O01.png,Vlad_Bitting1_O02.png,Vlad_Bitting1_O03.png,Vlad_Bitting1_O04.png,Vlad_Bitting1_O05.png,Vlad_Bitting1_O06.png,Vlad_Bitting1_O07.png,Vlad_Bitting1_O08.png]
        - [Vlad_Bitting1_NO01.png,Vlad_Bitting1_NO02.png,Vlad_Bitting1_NO03.png,Vlad_Bitting1_NO04.png,Vlad_Bitting1_NO05.png,Vlad_Bitting1_NO06.png,Vlad_Bitting1_NO07.png,Vlad_Bitting1_NO08.png]			
      ancho_base: 1 #tiles
      alto_base: 1 #tiles
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 10 #pixels
      fps: 10
    - nombre: mago
      imagen:
        - [testxyh_N1.png,testxyh_N2.png,testxyh_N3.png,testxyh_N4.png]
        - [testxyh_NE1.png,testxyh_NE2.png,testxyh_NE3.png,testxyh_NE4.png]
        - [testxyh_E1.png,testxyh_E2.png,testxyh_E3.png,testxyh_E4.png]
        - [testxyh_SE1.png,testxyh_SE2.png,testxyh_SE3.png,testxyh_SE4.png]
        - [testxyh_S1.png,testxyh_S2.png,testxyh_S3.png,testxyh_S4.png]
        - [testxyh_SO1.png,testxyh_SO2.png,testxyh_SO3.png,testxyh_SO4.png]
        - [testxyh_O1.png,testxyh_O2.png,testxyh_O3.png,testxyh_O4.png]
        - [testxyh_NO1.png,testxyh_NO2.png,testxyh_NO3.png,testxyh_NO4.png]
      fps: 10
      pixel_ref_x: 40 #pixels
      pixel_ref_y: 15 #pixels
escenarios:
    - nombre: bosque_encantado
      size_x: 200 #tiles
      size_y: 200 #tiles
      entidadesDef:
        - {x: 1, y: 40, entidad: agua}
        - {x: 1, y: 41, entidad: agua}
        - {x: 2, y: 40, entidad: agua}
        - {x: 2, y: 41, entidad: agua}
        - {x: 1, y: 40, entidad: molino}

        - {x: 4, y: 40, entidad: agua}
        - {x: 4, y: 41, entidad: agua}
        - {x: 5, y: 40, entidad: agua}
        - {x: 5, y: 41, entidad: agua}
        - {x: 4, y: 40, entidad: rancho}

        - {x: 7, y: 40, entidad: agua}
        - {x: 7, y: 41, entidad: agua}
        - {x: 8, y: 40, entidad: agua}
        - {x: 8, y: 41, entidad: agua}
        - {x: 7, y: 40, entidad: granja_llamas}


        - {x: 10, y: 40, entidad: agua}
        - {x: 10, y: 41, entidad: agua}
        - {x: 10, y: 42, entidad: agua}
        - {x: 11, y: 40, entidad: agua}
        - {x: 11, y: 41, entidad: agua}
        - {x: 11, y: 42, entidad: agua}
        - {x: 12, y: 40, entidad: agua}
        - {x: 12, y: 41, entidad: agua}
        - {x: 12, y: 42, entidad: agua}
        - {x: 10, y: 40, entidad: casa_molino}

        - {x: 14, y: 40, entidad: agua}
        - {x: 14, y: 41, entidad: agua}
        - {x: 14, y: 42, entidad: agua}
        - {x: 14, y: 43, entidad: agua}
        - {x: 15, y: 40, entidad: agua}
        - {x: 15, y: 41, entidad: agua}
        - {x: 15, y: 42, entidad: agua}
        - {x: 15, y: 43, entidad: agua}
        - {x: 16, y: 40, entidad: agua}
        - {x: 16, y: 41, entidad: agua}
        - {x: 16, y: 42, entidad: agua}
        - {x: 16, y: 43, entidad: agua}
        - {x: 17, y: 40, entidad: agua}
        - {x: 17, y: 41, entidad: agua}
        - {x: 17, y: 42, entidad: agua}
        - {x: 17, y: 43, entidad: agua}
        - {x: 14, y: 40, entidad: castillo}

        - {x: 19, y: 40, entidad: agua}
        - {x: 19, y: 41, entidad: agua}
        - {x: 19, y: 42, entidad: agua}
        - {x: 20, y: 40, entidad: agua}
        - {x: 20, y: 41, entidad: agua}
        - {x: 20, y: 42, entidad: agua}
        - {x: 21, y: 40, entidad: agua}
        - {x: 21, y: 41, entidad: agua}
        - {x: 21, y: 42, entidad: agua}
        - {x: 19, y: 40, entidad: casa_selva}
        
        - {x: 23, y: 40, entidad: agua}
        - {x: 23, y: 41, entidad: agua}
        - {x: 24, y: 40, entidad: agua}
        - {x: 24, y: 41, entidad: agua}
        - {x: 23, y: 40, entidad: mini_mapa}
      protagonista:
        - entidad: vlad
          x: 0
          y: 40