# Archivo de configuración
pantalla:
    ancho: 800 #pixels
    alto: 600 #pixels
configuracion:
    vel_personaje : 3
    margen_scroll : 30
entidades:
    - nombre: arbol
      imagen:
        - [default.png]
        - [default.png,default.png,default.png]
    - nombre: castillo
      imagen:
        - [default.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
    - nombre: orco
      imagen:
        - [default.png]
      fps: 10
      delay: 5
    - nombre: frodo
      imagen:
        - [default.png,default.png]
        - [default.png,default.png]
        - [default.png,default.png]
        - [default.png,default.png]
        - [default.png,default.png]
        - [default.png,default.png]
        - [default.png,default.png]
        - [default.png,default.png]
      fps: 10
      ancho_base: 30 #tiles
      alto_base: 30 #tiles
    - nombre: tierra
      imagen:
        - [default.png]
    - nombre: agua
      imagen:
        - [default.png]
escenarios:
    - nombre: bosque_encantado
      size_x: 50 #tiles
      size_y: 50 #tiles
      entidadesDef:
        - {x: 10, y: 15, entidad: tierra}
        - {x: 15, y: 20, entidad: tierra}
        - {x: 10, y: 15, entidad: agua}
        - {x: 30, y: 55, entidad: castillo}
      protagonista:
        - entidad: frodo
          x: 50
          y: 50