# <<<Este es sólo un archivo de ejemplo para ver la estructura del un archivo YAML>>>
juego:
pantalla:
    ancho: 800
    alto: 600 #Comentario
parametros:
    vel_personaje: 400
    margen_scroll: 200
texturas:
    viga: metal.png
    madera: madera.png  #madera: madera.png
nivel:
    ancho: 1600
    alto: 600
    fondo: fondo.png