# Archivo de configuración
pantalla:
    ancho: 800 #pixels
    alto: 600 #pixels
configuracion:
    vel_personaje : 200
    margen_scroll : 30
entidades:
    - nombre: arbol
      imagen:
        - [default.png]
        - [default.png,default.png,default.png]
    - nombre: castillo
      imagen:
        - [castillo01.png,castillo02.png,castillo03.png,castillo04.png,castillo05.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
    - nombre: orco
      imagen:
        - [default.png]
      fps: 10
      delay: 5
    - nombre: frodo
      imagen:
        - [testxyh_N1.png,testxyh_N2.png,testxyh_N3.png,testxyh_N4.png]
        - [testxyh_NE1.png,testxyh_NE2.png,testxyh_NE3.png,testxyh_NE4.png]
        - [testxyh_E1.png,testxyh_E2.png,testxyh_E3.png,testxyh_E4.png]
        - [testxyh_SE1.png,testxyh_SE2.png,testxyh_SE3.png,testxyh_SE4.png]
        - [testxyh_S1.png,testxyh_S2.png,testxyh_S3.png,testxyh_S4.png]
        - [testxyh_SO1.png,testxyh_SO2.png,testxyh_SO3.png,testxyh_SO4.png]
        - [testxyh_O1.png,testxyh_O2.png,testxyh_O3.png,testxyh_O4.png]
        - [testxyh_NO1.png,testxyh_NO2.png,testxyh_NO3.png,testxyh_NO4.png]
      fps: 10
      pixel_ref_x: 40 #pixels
      pixel_ref_y: 15 #pixels
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
    - nombre: tierra
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 0 #pixels
      ancho_base: 1 #tiles
      alto_base: 1 #tiles
      imagen:
        - [tierra.png]
    - nombre: agua
      pixel_ref_x: 50 #pixels
      pixel_ref_y: 0 #pixels
      ancho_base: 1 #tiles
      alto_base: 1 #tiles
      imagen:
        - [hielo.png]
escenarios:
    - nombre: bosque_encantado
      size_x: 20 #tiles
      size_y: 20 #tiles
      entidadesDef:
        - {x: 10, y: 15, entidad: tierra}
        - {x: 15, y: 19, entidad: tierra}
        - {x: 10, y: 15, entidad: agua}
        - {x: 5, y: 5, entidad: castillo}
      protagonista:
        - entidad: frodo
          x: 0
          y: 0