# Archivo de configuración
pantalla:
    ancho: 800 #pixels
    alto: 600 #pixels
configuracion:
    vel_personaje : 3
    margen_scroll : 100
entidades:
    - nombre: tierra
      imagen:
        - [tierra.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: hielo
      imagen:
        - [hielo.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: pasto
      imagen:
        - [pasto.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: agua
      imagen:
        - [agua.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: cemento
      imagen:
        - [cemento.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: arena
      imagen:
        - [arena.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: casaMolino
      imagen:
        - [FireFarm01.png,FireFarm02.png,FireFarm03.png,FireFarm04.png,FireFarm05.png,FireFarm06.png,FireFarm07.png,FireFarm08.png,FireFarm09.png,FireFarm10.png,FireFarm11.png,FireFarm12.png,FireFarm13.png,FireFarm14.png,FireFarm15.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: casaMolino
      imagen:
        - [CasaB01.png,CasaB02.png,CasaB03.png,CasaB04.png,CasaB05.png,CasaB06.png,CasaB07.png,CasaB08.png,CasaB09.png,CasaB10.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: castillo
      imagen:
        - [castillo01.png,castillo02.png,castillo03.png,castillo04.png,castillo05.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: casaSelva
      imagen:
        - [CasaC01.png,CasaC02.png,CasaC03.png,CasaC04.png,CasaC04.png,CasaC06.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: rancho
      imagen:
        - [CasaA01.png,CasaA02.png,CasaA03.png,CasaA04.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: miniMapa
      imagen:
        - [MiniMapa01.png,MiniMapa02.png,MiniMapa03.png,MiniMapa04.png,MiniMapa05.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: molino
      imagen:
        - [molino01.png,molino02.png,molino03.png,molino04.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: violeta
      imagen:
        - [6Actor_N1.png,6Actor_N2.png,6Actor_N3.png,6Actor_N4.png,6Actor_N5.png,6Actor_N6.png]
        - [6Actor_NE1.png,6Actor_NE2.png,6Actor_NE3.png,6Actor_NE4.png,6Actor_NE5.png,6Actor_NE6.png]
        - [6Actor_E1.png,6Actor_E2.png,6Actor_E3.png,6Actor_E4.png,6Actor_E5.png,6Actor_E6.png]
        - [6Actor_SE1.png,6Actor_SE2.png,6Actor_SE3.png,6Actor_SE4.png,6Actor_SE5.png,6Actor_SE6.png]
        - [6Actor_S1.png,6Actor_S2.png,6Actor_S3.png,6Actor_S4.png,6Actor_S5.png,6Actor_S6.png]
        - [6Actor_SO1.png,6Actor_SO2.png,6Actor_SO3.png,6Actor_SO4.png,6Actor_SO5.png,6Actor_SO6.png]
        - [6Actor_O1.png,6Actor_O2.png,6Actor_O3.png,6Actor_O4.png,6Actor_O5.png,6Actor_O6.png]
        - [6Actor_NO1.png,6Actor_NO2.png,6Actor_NO3.png,6Actor_NO4.png,6Actor_NO5.png,6Actor_NO6.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: guerrero
      imagen:
        - [actor1N1.png,actor1N2.png,actor1N3.png,actor1N4.png]
        - [actor1NE1.png,actor1NE2.png,actor1NE3.png,actor1NE4.png]
        - [actor1E1.png,actor1E2.png,actor1E3.png,actor1E4.png]
        - [actor1SE1.png,actor1SE2.png,actor1SE3.png,actor1SE4.png]
        - [actor1S1.png,actor1S2.png,actor1S3.png,actor1S4.png]
        - [actor1SO1.png,actor1SO2.png,actor1SO3.png,actor1SO4.png]
        - [actor1O1.png,actor1O2.png,actor1O3.png,actor1O4.png]
        - [actor1NO1.png,actor1NO2.png,actor1NO3.png,actor1NO4.png]
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
    - nombre: mago
      imagen:        
        - [testxyh_N1.png,testxyh_N2.png,testxyh_N3.png,testxyh_N4.png]
        - [testxyh_NE1.png,testxyh_NE2.png,testxyh_NE3.png,testxyh_NE4.png]
        - [testxyh_E1.png,testxyh_E2.png,testxyh_E3.png,testxyh_E4.png]
        - [testxyh_SE1.png,testxyh_SE2.png,testxyh_SE3.png,testxyh_SE4.png]
        - [testxyh_S1.png,testxyh_S2.png,testxyh_S3.png,testxyh_S4.png]    
        - [testxyh_SO1.png,testxyh_SO2.png,testxyh_SO3.png,testxyh_SO4.png]            
        - [testxyh_O1.png,testxyh_O2.png,testxyh_O3.png,testxyh_O4.png]        
        - [testxyh_NO1.png,testxyh_NO2.png,testxyh_NO3.png,testxyh_NO4.png]        
      ancho_base: 2 #tiles
      alto_base: 2 #tiles
      pixel_ref_x: 30 #pixels
      pixel_ref_y: 40 #pixels
      fps: 10
      delay: 5
escenarios:
    - nombre: bosque_encantado
      size_x: 200 #tiles
      size_y: 200 #tiles
      entidadesDef:
        - {x: 10, y: 40, entidad: casaMolino}
        - {x: 15, y: 40, entidad: castillo}
        - {x: 20, y: 40, entidad: casaSelva}
        - {x: 25, y: 40, entidad: molino}
        - {x: 30, y: 40, entidad: rancho}
        - {x: 35, y: 40, entidad: miniMapa}
        - {x: 40, y: 40, entidad: guerrero}
        - {x: 45, y: 40, entidad: violeta}
      protagonista:
        - entidad: mago
          x: 0
          y: 40